config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "register" }

  resources :invitations do
    resources :events
  end

  get 'pages/about'

  get 'pages/contact'

  get 'pages/index'

  root 'pages#index'

end

app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to :invitation, dependent: :destroy

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base

	belongs_to :user, dependent: :destroy

	has_many :events

	accepts_nested_attributes_for :events

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_filter :load_invitation

	def new
		@event = @invitation.events.build
	end

	def create
    @event = @invitation.events.build(event_params)
    @event.invitation_id = @invitation.id

    if @event.save
      redirect_to invitation_path(@invitation), notice: "Event successfully added."
    else
      render :new
    end
  end

	def edit
		@event = Event.find(params[:id])
	end

	def update
    @event = @invitation.events.find(params[:id])

		if @event.update_attributes(event_params)
      redirect_to invitation_path(@invitation), notice: "Event successfully updated."
    else
      render :edit
    end
	end

	def show
    @event = Event.find(params[:id])
  end

	protected

	def event_params
    params.require(:event).permit(:name, :date, :time, :location, :rsvp, :notes, :order, :invitation_id)
  end

  def load_invitation
    @invitation = Invitation.find(params[:invitation_id])
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update,   :destroy]
  # before_filter :check_user, only: [:edit, :update, :destroy]

	def index
		@invitations = Invitation.all
	end

	def new
		@invitation = Invitation.new
	end

	def edit
    @invitation = Invitation.find(params[:id])
	end

  def update
    @invitation = Invitation.find(params[:id])

    if @invitation.update_attributes(invitation_params)
      redirect_to invitation_path(@invitation)
    else
      render :edit
    end
  end

	def show
    @invitation = Invitation.find(params[:id])
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy
    redirect_to root_path, notice: "Invitation was deleted successfully"
  end

  def create
  	@invitation = Invitation.new(invitation_params)
    @invitation.user_id = current_user.id

  if @invitation.save
    redirect_to invitation_path(@invitation), notice: "Invitation was submitted successfully!"
  else
    render :new
  end
  end

  protected

  def invitation_params
    params.require(:invitation).permit(
      :date, :location, :bridename, :bridephone, :brideemail, :bridebio, :groomname, :groomphone, :groomemail, :groombio, :user_id
    )
  end

  # def check_user
  #   if current_user != @invitation.user
  #     redirect_to root_path, alert: "Sorry, you cannot edit this listing."
  #   end
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/edit.html.erb
<h2>Edit event.</h2>

<%= form_for([@invitation, @event]) do |f| %>
  <div class="form-group">
    <%= f.label "Name" %><br/>
    <%= f.text_field "name", autofocus: true, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label "Date" %><br/>
    <%= f.date_field "date", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Time" %><br/>
    <%= f.datetime_field "time", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Location" %><br/>
    <%= f.text_field "location", class: "form-control" %>
  </div>
  <div class="form-group">
  	<%= f.label "RSVP?" %><br/>
  	<%= f.select :rsvp, [['Yes', true], ['No', false]] %>
  </div>
  <div class="form-group">
  	<%= f.label "Event Notes" %>
  	<%= f.text_field "notes", class: "form-control" %>
  </div>
  <div class="form-group">
  	<%= f.label "Event Order" %>
  	<%= f.number_field "order", class: "form-control" %>
  <br/><div class="form-group">
  	<%= submit_tag "Save Changes", class: "btn btn-primary btn-wide" %>
	</div>
<% end %>

app/views/events/new.html.erb
<h2>Add event.</h2>

<%= form_for([@invitation, @event]) do |f| %>
  <div class="form-group">
    <%= f.label "Name" %><br/>
    <%= f.text_field "name", autofocus: true, class: "form-control" %>
  </div>  
  <div class="form-group">
    <%= f.label "Date" %><br/>
    <%= f.date_field "date", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Time" %><br/>
    <%= f.datetime_field "time", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Location" %><br/>
    <%= f.text_field "location", class: "form-control" %>
  </div>
  <div class="form-group">
  	<%= f.label "RSVP?" %><br/>
  	<%= f.select :rsvp, [['Yes', true], ['No', false]] %>
  </div>
  <div class="form-group">
  	<%= f.label "Event Notes" %>
  	<%= f.text_field "notes", class: "form-control" %>
  </div>
  <div class="form-group">
  	<%= f.label "Event Order" %>
  	<%= f.number_field "order", class: "form-control" %>
  <br/><div class="form-group">
  	<%= submit_tag "Add Event", class: "btn btn-primary btn-wide" %>
	</div>
<% end %>

app/views/events/show.html.erb
<h2>View event.</h2><br/>

<h4><%= @event.name %></h4>
<% if @event.rsvp %>
<p>Please <a href="#">RSVP</a>.</p>
<% else %>
<p>No RSVP Required.</p>
<% end %>
<p><%= @event.date.strftime("%B %d, %Y") %> - <%= @event.time.strftime("%l:%M %P") %></p>
<p><%= @event.location %></p>
<p><%= @event.notes %></p>
<%= link_to 'Edit Event', edit_invitation_event_path %>

app/views/invitations/edit.html.erb
<h1>Edit Invitation</h1>

<%= form_for(@invitation) do |f| %>

  <div class="row">
    <div class="col-md-6">
      <h5>Date</h5>
      <div class="form-group">
      <%= f.date_field "date", class: "form-control" %>
      </div>
    </div>
  
    <div class="col-md-6">
      <h5>Location</h5>
      <div class="form-group">
      <%= f.text_field "location", class: "form-control" %>
      </div>
    </div>
  </div>

  <br/><div class="row">

  <div class="col-md-6">
  <h5>Groom Info</h5>
  <div class="form-group">
    <%= f.label "Groom Name" %><br/>
    <%= f.text_field "groomname", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label "Groom Phone" %><br/>
    <%= f.text_field "groomphone", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label "Groom Email" %><br/>
    <%= f.text_field "groomemail", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label "Groom Bio" %><br/>
    <%= f.text_area "groombio", class: "form-control", :rows => 4 %>
  </div>
  </div>

  <div class="col-md-6">
  <h5>Bride Info</h5>  
  <div class="form-group">
    <%= f.label "Bride Name" %><br/>
    <%= f.text_field "bridename", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Bride Phone" %><br/>
    <%= f.text_field "bridephone", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Bride Email" %><br/>
    <%= f.text_field "brideemail", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Bride Bio" %><br/>
    <%= f.text_area "bridebio", class: "form-control", :rows => 4 %>
  </div>
  </div>

  </div>

  <br/><div><%= submit_tag "Save Changes", class: "btn btn-primary btn-wide" %></div>
<% end %>

app/views/invitations/index.html.erb
<% @invitations.each do |e| %>
<%= e.groomname %> and <%= e.bridename %> 
(<%= e.date.strftime("%B %d, %Y") %> at
<%= e.location %>)<br/>
<% end %>

app/views/invitations/new.html.erb
<h1>New Invitation</h1>

<%= form_for(@invitation) do |f| %>

  <div class="row">
    <div class="col-md-6">
      <h5>Date</h5>
      <div class="form-group">
      <%= f.date_field "date", autofocus: true, class: "form-control" %>
      </div>
    </div>
  
    <div class="col-md-6">
      <h5>Location</h5>
      <div class="form-group">
      <%= f.text_field "location", class: "form-control" %>
      </div>
    </div>
  </div>

  <br/><div class="row">

  <div class="col-md-6">
  <h5>Groom Info</h5>
  <div class="form-group">
    <%= f.label "Groom Name" %><br/>
    <%= f.text_field "groomname", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label "Groom Phone" %><br/>
    <%= f.text_field "groomphone", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label "Groom Email" %><br/>
    <%= f.text_field "groomemail", class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label "Groom Bio" %><br/>
    <%= f.text_area "groombio", class: "form-control", :rows => 4 %>
  </div>
  </div>

  <div class="col-md-6">
  <h5>Bride Info</h5>  
  <div class="form-group">
    <%= f.label "Bride Name" %><br/>
    <%= f.text_field "bridename", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Bride Phone" %><br/>
    <%= f.text_field "bridephone", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Bride Email" %><br/>
    <%= f.text_field "brideemail", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Bride Bio" %><br/>
    <%= f.text_area "bridebio", class: "form-control", :rows => 4 %>
  </div>
  </div>

  </div>

  <br/><div><%= submit_tag "Create Invitation", class: "btn btn-primary btn-wide" %></div>
<% end %>

app/views/invitations/show.html.erb
<center>

<p style="color:#8E44AD;font-size:65px;font-family:Pinyon Script;"><%= @invitation.groomname %> &amp; <%= @invitation.bridename %></p>
<h4>are getting married!</h4>
<h4><%= @invitation.date.strftime("%B %d, %Y") %></h4>
<h4><%= @invitation.location %></h4>
<br/>

<p style="color:#8E44AD;font-family:Pinyon Script;font-size:46px;">Events</p>

<% @invitation.events.each do |e| %>
    <h4><%= e.name %></h4>
    <% if e.rsvp %>
    <p>Please <a href="#">RSVP</a></p>
    <% else %>
    <p>No RSVP Required.</p>
    <% end %>
    <p><%= e.date.strftime("%B %d, %Y") %> - <%= e.time.strftime("%l:%M %P") %></p>
    <p><%= e.location %></p>
    <p><%= e.notes %></p>
    <% if user_signed_in? %>
    <p><%= link_to 'View/Edit', invitation_event_path(@invitation, e) %></p>
    <% end %><br/>
<% end %>

    <h5><% if user_signed_in? %>
    <%= link_to 'Add Event', new_invitation_event_path(@invitation) %>.
    <% end %></h5>

<p style="color:#8E44AD;font-family:Pinyon Script;font-size:46px;">Contact Info</p>

<div class="row">

<div class="col-md-6"><strong><%= @invitation.groomname %></strong><br/><%= @invitation.groomphone %><br/><%= @invitation.groomemail %></div>

<div class="col-md-6"><strong><%= @invitation.bridename %></strong><br/><%= @invitation.bridephone %><br/><%= @invitation.brideemail %></div>

</div></br>

<% if user_signed_in? %>
<h5><%= link_to 'Edit Invitation', edit_invitation_path %>.
<%= link_to 'Delete Invitation', @invitation, method: :delete, data: { confirm: 'Are you sure?' } %>.</h5>
<% end %>

<p style="font-size:48px;font-family:Great Vibes;">We look forward to celebrating with you!</p>

</center>

app/views/layouts/_footer.html.erb
<br/>
<hr/>
<p>Copyright 2014 - <a href="http://raize.ca/">Raize Web Marketing</a></p>

app/views/layouts/_header.html.erb
<center><%= link_to root_path do %>
  <%= image_tag "logo2.png"  %>
<% end %></center><br/>

<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">

<ul class="nav navbar-nav">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "About", pages_about_path %></li>
<li><%= link_to "Contact", pages_contact_path %></li>
</ul>

<ul class="nav navbar-nav navbar-right">
<% if user_signed_in? %>
<li><%= link_to "New Invitation", new_invitation_path %></li>
<li><%= link_to "Edit Account", edit_user_registration_path %></li>
<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
<% else %>
<li><%= link_to "Register", new_user_registration_path %></li>
<li><%= link_to "Sign In", new_user_session_path %></li>
<% end %>
</ul>

</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
  <title>invitely.io - digital wedding invitations</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Pinyon+Script|Great+Vibes">

</head>
<body>

<%= render 'layouts/header' %>

<div class="container"></br>

<center><p class="notice"><%= notice %></p></center>
<center><p class="alert"><%= alert %></p></center>

<%= yield %>

<%= render 'layouts/footer' %>

</div>

</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p style="color:#7f8c8d;">Invitely is an online web service where you can create and send digital wedding invitations to your guests.</p>
<p style="color:#7f8c8d;">In 2013, I was getting married and was in charge of planning a wedding for 600 guests (I'm Indian, what did you expect). With some guests coming from out of town, and others spread all over BC, the task of sending out wedding invitations became overwhelming. Especially since I'm a perfectionist who wanted to design and print my own wedding invitations. 
<p style="color:#7f8c8d;">As my wedding day came closer and closer, I realized I didn't have enough time to get all the invitations out. So I did what any saavy web developer in my position would do. I created an online web page with all of our wedding details. I even included a pre-wedding photo gallery, and a little backgroung information about me and my wife. I sent it to my friends through Facebook and Email, hoping that they would take it seriously. The response was amazing! Everyone loved it, and more importantly, everyone showed up! Since then, many of my friends have been asking me to create digital wedding invitiations for them as well, so I decided to turn my idea into a web app that anyone could use.</p>
<p style="color:#7f8c8d;">Please send me any feedback you may have, as I'd like this to be a useful service for everyone. In the future, I would love to add the ability to create invitations for other events as well. Thanks for visiting my site, talk to you soon!</p>

<p>Simon Rai<br/>
simon@raize.ca</p>

app/views/pages/contact.html.erb
<div class="row">

  <div class="col-md-6">
  	<h6>Get In Touch With Me</h6>
  	<hr/>
  	<p style="color:#7f8c8d;">For any inquiries about using invitely or customizing your invitation feel free to contact me.</p>
  	<p><a href="tel:6043389687"><span class="glyphicon glyphicon-earphone"></span>  604-338-9687</a></p>
  	<p><a href="email:simon@raize.ca"><span class="glyphicon glyphicon-envelope"></span>  simon@raize.ca</a></p>
  	<p><a href="http://twitter.com/simonrai_"><span class="glyphicon glyphicon-share-alt"></span>  @simonrai_</a></p><br/>
  	<h6>Where To Find Me</h6>
  	<hr/>
  	<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2602.7102579857547!2d-123.10818774999998!3d49.28188719999999!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5486717986699687%3A0x4fb885f79ca787fa!2s128+W+Hastings+St!5e0!3m2!1sen!2sca!4v1399408716830" width="400" height="200" frameborder="0" style="border:0"></iframe>
  </div>

  <div class="col-md-6">
  	<h6>Email Me</h6>
  	<hr/>
  	<form role="form">

  		<div class="form-group">
    		<label>Name</label>
    		<input type="email" class="form-control" placeholder="Enter name" autofocus>
  		</div>

  		<div class="form-group">
    		<label>Email</label>
    		<input type="text" class="form-control" placeholder="Enter email">
  		</div>

  		<div class="form-group">
    		<label>Message</label>
    		<textarea class="form-control" placeholder="Enter message" rows="5"></textarea>
  		</div>

  		<button type="submit" class="btn btn-primary btn-wide">Submit</button>
  
  	</form>
	
	</div>

</div>

app/views/pages/index.html.erb
<center><h5>Invitely makes sending wedding invitations fast, easy, and affordable.</h5></center><br/><br/>
<hr/><br/>

<div class="row">
<div class="col-md-4" style="text-align:center;">
<%= image_tag("clipboard.png", width: '104', height: '104') %>
<h6 style="color:#1ABC9C;">1. Enter Wedding Details</h6>
<p style="color:#7f8c8d;">Whether it's a pre-wedding party, ceremony or reception, customize your invitation by adding the events you want. Guests can RSVP for the events that you choose!</p>
</div>
<div class="col-md-4" style="text-align:center;">
<%= image_tag("flag.png", width: '104', height: '104') %>
<h6 style="color:#1ABC9C;">2. Choose A Design</h6>
<p style="color:#7f8c8d;">We utilize cutting edge technologies like HTML5, Javascript, and CSS3 to ensure your invitation can be viewed on any internet device with a beautiful user experience.
</div>
<div class="col-md-4" style="text-align:center;">
<%= image_tag("target.png", width: '104', height: '104') %>
<h6 style="color:#1ABC9C;">3. Send To Your Guests</h6>
<p style="color:#7f8c8d;">Once you're invitation is complete send it to your guests at the click of a button. Each invitation is password protected, so only the guests you've contacted will be able to view it.
</div>
</div>
<hr/><br/>
<center>
<p class="lead">We've taken the hastle out of sending wedding invitations because we know you'd rather be doing other things before your big day. </p>
<p class="lead">All it takes is a few minutes to design and send your wedding invitations. Your guests instantly recieve a beautiful, digital wedding invitation, with all the information they need for your wedding.</p>
<p class="lead">There's simply no better way to create and send wedding invitations. Try it for free!</p>
</center>

<% if user_signed_in? %>
<center><%= link_to "Create Invitation", new_invitation_path, class: "btn btn-hg btn-primary" %></center>
<% else %>
<center><%= link_to "Create Invitation", new_user_registration_path, class: "btn btn-hg btn-primary" %></center>
<% end %>